version: '3'
services:
  mongo:
    image: mongo:4.0
    container_name: mongo4.0
    #restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /Users/viky/mongodb/db:/data/db
    command: [--auth]
    networks:
      - backend
networks:
  backend: 