version: '3' 
services:
  redis:
    image: redis:4.0-alpine
    container_name: redis4.0
    volumes:
      - ./redis/data:/data
    ports:
      - "6380:6379"
    networks:
      - backend 
    sysctls:
      net.core.somaxconn: '511' 
networks:
  backend: 