version: '3'
# 定义四个服务nginx,php,mysql
services:
  nginx:
      image : nginx:alpine
      # 容器名称
      container_name: nginx
      # 这样使nginx容器把网站文件和目录存放到主机目录中，持久化和方便管理
      volumes:
        - ./nginx/www:/var/www
        - ./nginx/conf/conf.d/:/etc/nginx/conf.d/
        - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/log/:/var/log/nginx/
      # nginx意外退出时自动重启
      restart: always
      # 映射80和443端口
      ports:
        - "80:80"
      #  - "443:443"
      networks:
        - frontend
      depends_on:
        - php
      links:
        - php
      
  #php 
  php:
    image: wpengine/php:7.2
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      # - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      # - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      # - ./php/php.ini:/usr/local/php/etc/php.ini
      # - ./php/log/php-fpm.log:/usr/local/php/var/log/php-fpm.log
      #- ./nginx/www:/usr/share/nginx/html
      - ./nginx/www:/var/www  #此目录一定要跟nginx中配置的目录一样
    #restart: always
    networks:
      - frontend
      - backend   
  
  # MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - backend
    restart: always
   # redis 
  redis:
    image: redis:4.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - backend
    
    
networks:
  frontend:
  backend: