version: '3'
# 定义四个服务nginx,php,mysql
services:
  mysql5.7:
    image: mysql:5.7
    container_name: mysql5.7
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always